spring:
  application:
    name: order-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/dat-microservices
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:mysql://localhost:3307/db_order?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&useLegacyDatetimeCode=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8084

management:
  tracing:
    sampling:
      probability: 1.0  # 10% of the requests will be traced
    enabled: true  # Enable tracing
    baggage:
      remote-fields: "userId"

keycloak:
  client-id: ecommerce

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans  # Zipkin server URL for receiving spans
      connect-timeout: 1s  # Timeout for connecting to Zipkin server
      encoding: json  # The format of the trace data (you can use json or protobuf)
      read-timeout: 10s  # Timeout for reading from the Zipkin server

